import http from "http";
import https from "https";
import { NextRequest, NextResponse } from "next/server";
import { OLLAMA_MODEL } from "@/lib/markets/predictions";

// ─── Types ─────────────────────────────────────────────────────────────────────

interface ChatMessage {
  role: "system" | "user" | "assistant";
  content: string;
}

interface OllamaChatResponse {
  message?: { role: string; content: string };
  error?: string;
}

// ─── Ollama chat via Node http (bypasses Next.js fetch patching) ───────────────

const OLLAMA_URL = process.env.OLLAMA_URL || "http://localhost:11434";

function ollamaChat(messages: ChatMessage[]): Promise<string> {
  return new Promise((resolve, reject) => {
    const body = JSON.stringify({
      model: OLLAMA_MODEL,
      messages,
      stream: false,
      options: {
        temperature: 0.3,  // slightly higher than predictions for natural conversation
        num_predict: 400,  // chat replies should be concise
        num_ctx: 2048,
      },
    });

    const parsedUrl = new URL(`${OLLAMA_URL}/api/chat`);
    const isHttps = parsedUrl.protocol === "https:";
    const transport = isHttps ? https : http;

    const reqOptions = {
      hostname: parsedUrl.hostname,
      port: parsedUrl.port ? Number(parsedUrl.port) : isHttps ? 443 : 80,
      path: parsedUrl.pathname,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Content-Length": Buffer.byteLength(body),
      },
    };

    const timer = setTimeout(() => {
      req.destroy(new Error("Ollama chat timed out after 90 seconds"));
    }, 90_000);

    const req = transport.request(reqOptions, (res) => {
      let raw = "";
      res.setEncoding("utf8");
      res.on("data", (chunk: string) => { raw += chunk; });
      res.on("end", () => {
        clearTimeout(timer);
        if (res.statusCode !== 200) {
          let errMsg = raw;
          try { errMsg = (JSON.parse(raw) as OllamaChatResponse).error ?? raw; } catch { /* keep raw */ }
          reject(new Error(`Ollama ${res.statusCode}: ${errMsg}`));
          return;
        }
        try {
          const parsed = JSON.parse(raw) as OllamaChatResponse;
          resolve(parsed.message?.content ?? "");
        } catch {
          reject(new Error("Failed to parse Ollama chat response"));
        }
      });
    });

    req.on("error", (err: NodeJS.ErrnoException) => {
      clearTimeout(timer);
      if (err.code === "ECONNREFUSED") {
        reject(new Error("Ollama not reachable. Make sure it is running."));
      } else {
        reject(err);
      }
    });

    req.write(body);
    req.end();
  });
}

// ─── System prompt ──────────────────────────────────────────────────────────────

function buildSystemPrompt(context?: string): string {
  const base = `You are StockPulse AI Advisor, an expert financial analyst assistant embedded in a real-time paper trading platform.

Your role:
- Answer questions about stocks, crypto, market trends, technical indicators, and trading strategies
- Explain market concepts clearly (RSI, MACD, Bollinger Bands, support/resistance, etc.)
- Help users understand their signals and predictions generated by the platform
- Give balanced, educational analysis — never reckless "buy this now" advice

Tone: concise, professional, and friendly. Keep replies under 200 words unless the user asks for a deep dive.

IMPORTANT DISCLAIMER: Always note that this is educational/paper trading only, not real financial advice.`;

  if (context) {
    return `${base}\n\nCurrent market context from the platform:\n${context}`;
  }
  return base;
}

// ─── Route handler ──────────────────────────────────────────────────────────────

export async function POST(request: NextRequest) {
  let body: { message?: string; history?: ChatMessage[]; context?: string };
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid request body" }, { status: 400 });
  }

  const { message, history = [], context } = body;

  if (!message || typeof message !== "string" || message.trim().length === 0) {
    return NextResponse.json({ error: "message is required" }, { status: 400 });
  }

  // Build messages array: system + history (last 10 turns) + current message
  const messages: ChatMessage[] = [
    { role: "system", content: buildSystemPrompt(context) },
    ...history.slice(-10),  // keep last 10 turns to stay within context window
    { role: "user", content: message.trim() },
  ];

  try {
    const reply = await ollamaChat(messages);
    return NextResponse.json({ reply, modelUsed: OLLAMA_MODEL });
  } catch (error) {
    const msg = error instanceof Error ? error.message : String(error);
    console.error("[chat] Ollama error:", msg);
    return NextResponse.json(
      {
        reply: "I'm temporarily unavailable — Ollama may be offline or still loading. Please try again in a moment.",
        modelUsed: OLLAMA_MODEL,
        error: msg,
      },
      { status: 200 }  // 200 so the UI shows the fallback message gracefully
    );
  }
}
